const RP_DATA = {
    "civils": [
        // { "nom": "EXEMPLE", "statut": "Recherché dangereux" },
        // { "nom": "EXEMPLE", "statut": "Recherché" },
        // { "nom": "EXEMPLE", "statut": "Enregistré" },
        { "nom": "MEIA Ryan", "statut": "Aucun (Casier vierge)" },
        { "nom": "MARTIENEZ Manolo", "statut": "Aucun (Casier vierge)" },
        { "nom": "MENDEZ Thiago", "statut": "Aucun (Casier vierge)" },
        { "nom": "BOSSET Jason", "statut": "Aucun (Casier vierge)" },
        { "nom": "RAMIREZ Sombra", "statut": "Enregistré" },
        { "nom": "MITCHELL Pete", "statut": "Aucun (Casier vierge)" },
        { "nom": "DIAZ Paco", "statut": "Aucun (Casier vierge)" },
        { "nom": "TIMAU Ariitea", "statut": "Aucun (Casier vierge)" },
        { "nom": "DOLLS Amaya", "statut": "Aucun (Casier vierge)" },
        { "nom": "DOLLS Aria", "statut": "Aucun (Casier vierge)" },
        { "nom": "YAKIMORI Ayame", "statut": "Aucun (Casier vierge)" }
    ],
    "agents": [
        "Capitaine Miller (M-01)",
        "Lieutenant Winslow (M-02)", 
        "Lieutenant Winslow (M-03)", 
        "Sergent Mcdonuts (M-04)", 
        "Cadet Steel (M-13)",
        "Cadet Swatie (M-14)", 
        "Cadet Keller (M-15)", 
        "Cadet Rawlins (M-16)", 
        "Cadet Walker (M-18)", 
        "Rookie Vasquez (M-21)", 
        "Rookie Davidson (M-22)", 
        "Cadet Carter (M-24)",
        "Cadet Wilson (M-25)", 
        "Cadet Williams (M-26)"
    ],
    "infractions": [
        { "categorie": "CODE CIVIL - INFRACTIONS MINEURES", "nom": "Trouble à l'ordre public (Art. 6)", "amende": 200, "peine": 5 },
        { "categorie": "CODE CIVIL - INFRACTIONS MINEURES", "nom": "Trouble à l'ordre public [Récidive x1]", "amende": 400, "peine": 10 },
        { "categorie": "CODE CIVIL - INFRACTIONS MINEURES", "nom": "Trouble à l'ordre public [Récidive x2]", "amende": 600, "peine": 15 },
        { "categorie": "CODE CIVIL - INFRACTIONS MINEURES", "nom": "Conduite dangereuse (Art. 7)", "amende": 1000, "peine": 10 },
        { "categorie": "CODE CIVIL - INFRACTIONS MINEURES", "nom": "Conduite dangereuse [Récidive x1]", "amende": 2000, "peine": 20 },
        { "categorie": "CODE CIVIL - INFRACTIONS MINEURES", "nom": "Conduite dangereuse [Récidive x2]", "amende": 3000, "peine": 30 },
        { "categorie": "CODE CIVIL - INFRACTIONS MINEURES", "nom": "Excès de vitesse (> 100km/h)", "amende": 1500, "peine": 0 },

        { "categorie": "CODE CIVIL - INFRACTIONS MAJEURES", "nom": "Vol de bien d'autrui (Art. 8)", "amende": 2500, "peine": 20 },
        { "categorie": "CODE CIVIL - INFRACTIONS MAJEURES", "nom": "Vol de bien d'autrui [Récidive x1]", "amende": 5000, "peine": 40 },
        { "categorie": "CODE CIVIL - INFRACTIONS MAJEURES", "nom": "Vol de véhicule de service public", "amende": 7500, "peine": 50 },
        { "categorie": "CODE CIVIL - INFRACTIONS MAJEURES", "nom": "Vol de véhicule de service public [Récidive x1]", "amende": 15000, "peine": 100 },
        { "categorie": "CODE CIVIL - INFRACTIONS MAJEURES", "nom": "Refus d'obtempérer (Art. 9)", "amende": 3000, "peine": 30 },
        { "categorie": "CODE CIVIL - INFRACTIONS MAJEURES", "nom": "Refus d'obtempérer [Récidive x1]", "amende": 6000, "peine": 60 },
        { "categorie": "CODE CIVIL - INFRACTIONS MAJEURES", "nom": "Délit de fuite", "amende": 3500, "peine": 35 },
        { "categorie": "CODE CIVIL - INFRACTIONS MAJEURES", "nom": "Délit de fuite [Récidive x1]", "amende": 7000, "peine": 70 },
        { "categorie": "CODE CIVIL - INFRACTIONS MAJEURES", "nom": "Port d'arme illégal : Beretta (Art. 10)", "amende": 5000, "peine": 45 },
        { "categorie": "CODE CIVIL - INFRACTIONS MAJEURES", "nom": "Port d'arme illégal : Glock (Art. 10)", "amende": 9000, "peine": 50 },
        { "categorie": "CODE CIVIL - INFRACTIONS MAJEURES", "nom": "Port d'arme illégal : Uzi / Tec-9 (Art. 10)", "amende": 11000, "peine": 60 },
        { "categorie": "CODE CIVIL - INFRACTIONS MAJEURES", "nom": "Port d'arme illégal : AK-47 (Art. 10)", "amende": 15000, "peine": 80 },

        { "categorie": "CODE CIVIL - CRIMES GRAVES", "nom": "Agression physique (Art. 11)", "amende": 35000, "peine": 120 },
        { "categorie": "CODE CIVIL - CRIMES GRAVES", "nom": "Agression physique [Récidive x1]", "amende": 70000, "peine": 240 },
        { "categorie": "CODE CIVIL - CRIMES GRAVES", "nom": "Braquage : ATM (Art. 12)", "amende": 2000, "peine": 30 },
        { "categorie": "CODE CIVIL - CRIMES GRAVES", "nom": "Braquage : Supérette (Art. 12)", "amende": 2000, "peine": 40 },
        { "categorie": "CODE CIVIL - CRIMES GRAVES", "nom": "Braquage : Fleeca (Art. 12)", "amende": 10000, "peine": 90 },

        { "categorie": "STANDARDS (COMPLÉMENTS)", "nom": "Outrage à agent", "amende": 2500, "peine": 15 },
        { "categorie": "STANDARDS (COMPLÉMENTS)", "nom": "Outrage à agent [Récidive x1]", "amende": 5000, "peine": 30 },
        { "categorie": "STANDARDS (COMPLÉMENTS)", "nom": "Possession de stupéfiants", "amende": 1500, "peine": 15 },
        { "categorie": "STANDARDS (COMPLÉMENTS)", "nom": "Possession de stupéfiants [Récidive x1]", "amende": 3000, "peine": 30 },
        { "categorie": "STANDARDS (COMPLÉMENTS)", "nom": "Vente de stupéfiants (Trafic)", "amende": 8000, "peine": 60 },
        { "categorie": "STANDARDS (COMPLÉMENTS)", "nom": "Vente de stupéfiants [Récidive x1]", "amende": 16000, "peine": 120 },
        { "categorie": "STANDARDS (COMPLÉMENTS)", "nom": "Meurtre sur civil", "amende": 40000, "peine": 110 },
        { "categorie": "STANDARDS (COMPLÉMENTS)", "nom": "Meurtre sur agent", "amende": 50000, "peine": 120 }
    ]
};
